### ISSUE TITLE
Crash on Xelsword Occultist

### ISSUE THREAD

**Issue by cacophony-wj** [AwesomeJames2120/Degenerate-Dungeon#1]
I narrowed down the crash to the Xelsword Occultist. It requires the Butcher's Circus to be installed _and enabled_ (with full fucking data collection) or it will crash every time. Something about that DLC changes the way files are arranged and Xelsword makes his new mods that new way now. So the problem wasn't yours. It was mine.

**Comment by AwesomeJames2120** [comment]
Added part about dlc requirement at the top of the readme
