### ISSUE TITLE
Failure during Download

### ISSUE THREAD

**Issue by Lionsix** [AwesomeJames2120/Degenerate-Dungeon#8]
File GRADIENTS OVERHAUL V2 by Dan.rar no longer exists on Loverslab and or link is wrong or broken failing the download at 9/22 during the hashing phase. Any work around? such as ignoring the file or removing it from download lists?

[Darkest Dungeon Hash snipet.txt](https://github.com/AwesomeJames2120/Degenerate-Dungeon/files/6698028/Darkest.Dungeon.Hash.snipet.txt)

**Comment by sir132** [comment]
it seems as if dan had made a newer version of it on nexus
https://www.nexusmods.com/darkestdungeon/mods/1250?tab=description

**Comment by Lionsix** [comment]
Install seems to be working again, closing issue.
